/* ===========================================================
   CHARACTER DATABASE
   Single unified list - lvl 1-4 = beginner/elementary,
   lvl 5-8 = intermediate, lvl 9-10 = advanced.
   Tags: battle | feast | build  (thematic vocabulary)
=========================================================== */
const CHARACTER_DB = [
  // == LEVELS 1-4 · Elementary ==
  // People & basic
  {hz:'人',py:'rén',en:'person',lvl:1},{hz:'大',py:'dà',en:'big',lvl:1},
  {hz:'小',py:'xiǎo',en:'small',lvl:1},{hz:'我',py:'wǒ',en:'I/me',lvl:1},
  {hz:'你',py:'nǐ',en:'you',lvl:1},{hz:'他',py:'tā',en:'he/him',lvl:1},
  {hz:'她',py:'tā',en:'she/her',lvl:1},{hz:'们',py:'men',en:'plural suffix',lvl:1},
  {hz:'这',py:'zhè',en:'this',lvl:1},{hz:'那',py:'nà',en:'that',lvl:1},
  {hz:'什么',py:'shénme',en:'what',lvl:1},{hz:'哪',py:'nǎ',en:'which',lvl:1},
  {hz:'谁',py:'shéi',en:'who',lvl:1},{hz:'哪里',py:'nǎlǐ',en:'where',lvl:1},
  {hz:'为什么',py:'wèishéme',en:'why',lvl:1},{hz:'怎么',py:'zěnme',en:'how',lvl:1},
  // Nature
  {hz:'山',py:'shān',en:'mountain',lvl:1},{hz:'水',py:'shuǐ',en:'water',lvl:1},
  {hz:'火',py:'huǒ',en:'fire',lvl:1},{hz:'木',py:'mù',en:'wood/tree',lvl:1},
  {hz:'日',py:'rì',en:'sun/day',lvl:2},{hz:'月',py:'yuè',en:'moon/month',lvl:2},
  {hz:'天',py:'tiān',en:'sky/day',lvl:2},{hz:'地',py:'dì',en:'earth',lvl:2},
  {hz:'风',py:'fēng',en:'wind',lvl:2},{hz:'雨',py:'yǔ',en:'rain',lvl:2},
  {hz:'雪',py:'xuě',en:'snow',lvl:2},{hz:'云',py:'yún',en:'cloud',lvl:2},
  {hz:'石',py:'shí',en:'stone/rock',lvl:2},{hz:'土',py:'tǔ',en:'soil/earth',lvl:2},
  {hz:'草',py:'cǎo',en:'grass',lvl:2},{hz:'花',py:'huā',en:'flower',lvl:2},
  {hz:'树',py:'shù',en:'tree',lvl:2},{hz:'叶',py:'yè',en:'leaf',lvl:2},
  {hz:'果',py:'guǒ',en:'fruit',lvl:2},{hz:'海',py:'hǎi',en:'sea/ocean',lvl:2},
  {hz:'河',py:'hé',en:'river',lvl:2},{hz:'湖',py:'hú',en:'lake',lvl:2},
  // Direction & position
  {hz:'上',py:'shàng',en:'up/above',lvl:2},{hz:'下',py:'xià',en:'down/below',lvl:2},
  {hz:'中',py:'zhōng',en:'middle',lvl:2},{hz:'左',py:'zuǒ',en:'left',lvl:2},
  {hz:'右',py:'yòu',en:'right',lvl:2},{hz:'前',py:'qián',en:'front/before',lvl:2},
  {hz:'后',py:'hòu',en:'back/after',lvl:2},{hz:'里',py:'lǐ',en:'inside',lvl:2},
  {hz:'外',py:'wài',en:'outside',lvl:2},{hz:'旁',py:'páng',en:'beside',lvl:2},
  // Verbs
  {hz:'来',py:'lái',en:'to come',lvl:2},{hz:'去',py:'qù',en:'to go',lvl:2},
  {hz:'吃',py:'chī',en:'to eat',lvl:2},{hz:'喝',py:'hē',en:'to drink',lvl:2},
  {hz:'看',py:'kàn',en:'to look/see',lvl:2},{hz:'说',py:'shuō',en:'to speak',lvl:2},
  {hz:'跑',py:'pǎo',en:'to run',lvl:2},{hz:'玩',py:'wán',en:'to play',lvl:2},
  {hz:'睡',py:'shuì',en:'to sleep',lvl:2},{hz:'起',py:'qǐ',en:'to rise/get up',lvl:2},
  {hz:'走',py:'zǒu',en:'to walk/go',lvl:2},{hz:'站',py:'zhàn',en:'to stand',lvl:2},
  {hz:'坐',py:'zuò',en:'to sit',lvl:3},{hz:'买',py:'mǎi',en:'to buy',lvl:3},
  {hz:'卖',py:'mài',en:'to sell',lvl:3},{hz:'给',py:'gěi',en:'to give',lvl:3},
  {hz:'拿',py:'ná',en:'to take/hold',lvl:3},{hz:'放',py:'fàng',en:'to put/release',lvl:3},
  {hz:'开',py:'kāi',en:'to open/start',lvl:3},{hz:'关',py:'guān',en:'to close',lvl:3},
  {hz:'写',py:'xiě',en:'to write',lvl:3},{hz:'画',py:'huà',en:'to draw',lvl:3},
  {hz:'唱',py:'chàng',en:'to sing',lvl:3},{hz:'跳',py:'tiào',en:'to jump/dance',lvl:3},
  {hz:'打',py:'dǎ',en:'to hit/play',lvl:3},{hz:'问',py:'wèn',en:'to ask',lvl:3},
  {hz:'听',py:'tīng',en:'to listen',lvl:3},{hz:'想',py:'xiǎng',en:'to think/want',lvl:3},
  {hz:'知',py:'zhī',en:'to know',lvl:3},{hz:'道',py:'dào',en:'road/way',lvl:3},
  {hz:'用',py:'yòng',en:'to use',lvl:3},{hz:'做',py:'zuò',en:'to do/make',lvl:3},
  {hz:'有',py:'yǒu',en:'to have',lvl:3},{hz:'没',py:'méi',en:'not have',lvl:3},
  {hz:'是',py:'shì',en:'to be',lvl:3},{hz:'不',py:'bù',en:'not/no',lvl:3},
  // Adjectives
  {hz:'爱',py:'ài',en:'love',lvl:3},{hz:'好',py:'hǎo',en:'good',lvl:3},
  {hz:'多',py:'duō',en:'many/much',lvl:3},{hz:'少',py:'shǎo',en:'few/little',lvl:3},
  {hz:'新',py:'xīn',en:'new',lvl:3},{hz:'旧',py:'jiù',en:'old/worn',lvl:3},
  {hz:'高',py:'gāo',en:'tall/high',lvl:3},{hz:'低',py:'dī',en:'low/short',lvl:3},
  {hz:'长',py:'cháng',en:'long',lvl:3},{hz:'短',py:'duǎn',en:'short',lvl:3},
  {hz:'快',py:'kuài',en:'fast',lvl:3},{hz:'慢',py:'màn',en:'slow',lvl:3},
  {hz:'冷',py:'lěng',en:'cold',lvl:3},{hz:'热',py:'rè',en:'hot',lvl:3},
  {hz:'干',py:'gān',en:'dry',lvl:3},{hz:'湿',py:'shī',en:'wet',lvl:3},
  {hz:'甜',py:'tián',en:'sweet',lvl:3},{hz:'苦',py:'kǔ',en:'bitter',lvl:3},
  {hz:'酸',py:'suān',en:'sour',lvl:3},{hz:'辣',py:'là',en:'spicy',lvl:3},
  // Colours
  {hz:'红',py:'hóng',en:'red',lvl:3},{hz:'黄',py:'huáng',en:'yellow',lvl:3},
  {hz:'绿',py:'lǜ',en:'green',lvl:3},{hz:'白',py:'bái',en:'white',lvl:3},
  {hz:'黑',py:'hēi',en:'black',lvl:3},{hz:'蓝',py:'lán',en:'blue',lvl:3},
  {hz:'紫',py:'zǐ',en:'purple',lvl:3},{hz:'橙',py:'chéng',en:'orange',lvl:3},
  {hz:'粉',py:'fěn',en:'pink',lvl:3},{hz:'灰',py:'huī',en:'grey',lvl:3},
  // Body
  {hz:'手',py:'shǒu',en:'hand',lvl:3},{hz:'眼',py:'yǎn',en:'eye',lvl:3},
  {hz:'口',py:'kǒu',en:'mouth',lvl:3},{hz:'耳',py:'ěr',en:'ear',lvl:3},
  {hz:'头',py:'tóu',en:'head',lvl:3},{hz:'脸',py:'liǎn',en:'face',lvl:3},
  {hz:'鼻',py:'bí',en:'nose',lvl:4},{hz:'牙',py:'yá',en:'tooth',lvl:4},
  {hz:'脚',py:'jiǎo',en:'foot/leg',lvl:4},{hz:'腿',py:'tuǐ',en:'leg',lvl:4},
  {hz:'肚',py:'dù',en:'belly/stomach',lvl:4},{hz:'背',py:'bèi',en:'back',lvl:4},
  // Family
  {hz:'家',py:'jiā',en:'home/family',lvl:4},{hz:'爸',py:'bà',en:'dad',lvl:4},
  {hz:'妈',py:'mā',en:'mum',lvl:4},{hz:'哥',py:'gē',en:'older brother',lvl:4},
  {hz:'姐',py:'jiě',en:'older sister',lvl:4},{hz:'弟',py:'dì',en:'younger brother',lvl:4},
  {hz:'妹',py:'mèi',en:'younger sister',lvl:4},{hz:'爷',py:'yé',en:'grandpa (dad)',lvl:4},
  {hz:'奶',py:'nǎi',en:'grandma (dad)',lvl:4},{hz:'姥',py:'lǎo',en:'grandma (mum)',lvl:4},
  // Animals
  {hz:'鸟',py:'niǎo',en:'bird',lvl:4},{hz:'鱼',py:'yú',en:'fish',lvl:4},
  {hz:'猫',py:'māo',en:'cat',lvl:4},{hz:'狗',py:'gǒu',en:'dog',lvl:4},
  {hz:'马',py:'mǎ',en:'horse',lvl:4},{hz:'牛',py:'niú',en:'cow/ox',lvl:4},
  {hz:'羊',py:'yáng',en:'sheep/goat',lvl:4},{hz:'猪',py:'zhū',en:'pig',lvl:4},
  {hz:'鸡',py:'jī',en:'chicken',lvl:4},{hz:'鸭',py:'yā',en:'duck',lvl:4},
  {hz:'兔',py:'tù',en:'rabbit',lvl:4},{hz:'蛇',py:'shé',en:'snake',lvl:4},
  {hz:'虫',py:'chóng',en:'insect/worm',lvl:4},{hz:'象',py:'xiàng',en:'elephant',lvl:4},
  {hz:'熊',py:'xióng',en:'bear',lvl:4},{hz:'狮',py:'shī',en:'lion',lvl:4},
  // Food & drink
  {hz:'饭',py:'fàn',en:'cooked rice/meal',lvl:4},{hz:'面',py:'miàn',en:'noodles/flour',lvl:4},
  {hz:'菜',py:'cài',en:'vegetable/dish',lvl:4},{hz:'肉',py:'ròu',en:'meat',lvl:4},
  {hz:'鱼',py:'yú',en:'fish',lvl:4},{hz:'蛋',py:'dàn',en:'egg',lvl:4},
  {hz:'米',py:'mǐ',en:'rice (uncooked)',lvl:4},{hz:'盐',py:'yán',en:'salt',lvl:4},
  {hz:'糖',py:'táng',en:'sugar/candy',lvl:4},{hz:'水果',py:'shuǐguǒ',en:'fruit',lvl:4},
  {hz:'苹果',py:'píngguǒ',en:'apple',lvl:4},{hz:'香蕉',py:'xiāngjiāo',en:'banana',lvl:4},
  // Numbers
  {hz:'一',py:'yī',en:'one',lvl:4},{hz:'二',py:'èr',en:'two',lvl:4},
  {hz:'三',py:'sān',en:'three',lvl:4},{hz:'四',py:'sì',en:'four',lvl:4},
  {hz:'五',py:'wǔ',en:'five',lvl:4},{hz:'六',py:'liù',en:'six',lvl:4},
  {hz:'七',py:'qī',en:'seven',lvl:4},{hz:'八',py:'bā',en:'eight',lvl:4},
  {hz:'九',py:'jiǔ',en:'nine',lvl:4},{hz:'十',py:'shí',en:'ten',lvl:4},
  {hz:'百',py:'bǎi',en:'hundred',lvl:4},{hz:'千',py:'qiān',en:'thousand',lvl:4},
  // Time
  {hz:'年',py:'nián',en:'year',lvl:4},{hz:'月',py:'yuè',en:'month',lvl:4},
  {hz:'日',py:'rì',en:'day',lvl:4},{hz:'今',py:'jīn',en:'today/now',lvl:4},
  {hz:'明',py:'míng',en:'tomorrow/bright',lvl:4},{hz:'昨',py:'zuó',en:'yesterday',lvl:4},
  {hz:'早',py:'zǎo',en:'morning/early',lvl:4},{hz:'晚',py:'wǎn',en:'evening/late',lvl:4},
  {hz:'午',py:'wǔ',en:'noon',lvl:4},{hz:'时',py:'shí',en:"time/o'clock",lvl:4},
  // Place & objects
  {hz:'门',py:'mén',en:'door/gate',lvl:4},{hz:'学',py:'xué',en:'to study/learn',lvl:4},
  {hz:'校',py:'xiào',en:'school',lvl:4},{hz:'书',py:'shū',en:'book',lvl:4},
  {hz:'桌',py:'zhuō',en:'table',lvl:4},{hz:'椅',py:'yǐ',en:'chair',lvl:4},
  {hz:'床',py:'chuáng',en:'bed',lvl:4},{hz:'房',py:'fáng',en:'room/house',lvl:4},
  {hz:'车',py:'chē',en:'vehicle/car',lvl:4},{hz:'路',py:'lù',en:'road/path',lvl:4},
  {hz:'店',py:'diàn',en:'shop/store',lvl:4},{hz:'市',py:'shì',en:'city/market',lvl:4},
  // Weather
  {hz:'太阳',py:'tàiyáng',en:'sun',lvl:4},{hz:'星',py:'xīng',en:'star',lvl:4},
  {hz:'光',py:'guāng',en:'light',lvl:4},{hz:'晴',py:'qíng',en:'sunny/clear',lvl:4},
  {hz:'阴',py:'yīn',en:'cloudy/overcast',lvl:4},{hz:'亮',py:'liàng',en:'bright',lvl:4},
  {hz:'暗',py:'àn',en:'dark',lvl:4},{hz:'热',py:'rè',en:'hot',lvl:4},
  // Journey to the West & pilgrimage vocabulary
  {hz:'经',py:'jīng',en:'scripture',lvl:5},{hz:'佛',py:'fó',en:'Buddha',lvl:5},
  {hz:'僧',py:'sēng',en:'monk',lvl:5},{hz:'妖',py:'yāo',en:'demon/spirit',lvl:5},
  {hz:'魔',py:'mó',en:'devil/demon',lvl:5},{hz:'怪',py:'guài',en:'monster/strange',lvl:5},
  {hz:'王',py:'wáng',en:'king',lvl:5},{hz:'国',py:'guó',en:'kingdom',lvl:5},
  {hz:'龙',py:'lóng',en:'dragon',lvl:5},{hz:'棒',py:'bàng',en:'staff/club',lvl:5},
  {hz:'扇',py:'shàn',en:'fan',lvl:5},{hz:'宝',py:'bǎo',en:'treasure',lvl:5},
  {hz:'洞',py:'dòng',en:'cave',lvl:5},{hz:'寺',py:'sì',en:'temple/monastery',lvl:5},
  {hz:'僧人',py:'sēngrén',en:'monk',lvl:5},{hz:'师父',py:'shīfu',en:'master',lvl:5},
  {hz:'徒弟',py:'túdì',en:'disciple',lvl:5},{hz:'护法',py:'hùfǎ',en:'protector of the Dharma',lvl:5},
  {hz:'法宝',py:'fǎbǎo',en:'magic treasure',lvl:5},{hz:'真经',py:'zhēnjīng',en:'true scripture',lvl:5},
  {hz:'取经',py:'qǔjīng',en:'to fetch the scriptures',lvl:5},{hz:'西行',py:'xīxíng',en:'journey west',lvl:5},
  {hz:'降妖',py:'xiángyāo',en:'to subdue demons',lvl:5},{hz:'除魔',py:'chúmó',en:'to banish evil',lvl:5},
  {hz:'变化',py:'biànhuà',en:'transformation',lvl:6},{hz:'分身',py:'fēnshēn',en:'clone/incarnation',lvl:6},
  {hz:'筋斗',py:'jīndǒu',en:'somersault',lvl:6},{hz:'腾云',py:'téngyún',en:'to ride the clouds',lvl:6},
  {hz:'天宫',py:'tiāngōng',en:'Heavenly Palace',lvl:6},{hz:'灵山',py:'língshān',en:'Sacred Mountain',lvl:6},
  {hz:'西天',py:'xītiān',en:'Western Heaven',lvl:6},{hz:'雷音',py:'léiyīn',en:'Thunderclap',lvl:6},
  {hz:'莲花',py:'liánhuā',en:'lotus',lvl:6},{hz:'袈裟',py:'jiāshā',en:'kasaya robe',lvl:6},
  {hz:'禅杖',py:'chánzhàng',en:'monk\'s staff',lvl:6},{hz:'紧箍咒',py:'jǐngūzhòu',en:'tightening spell',lvl:6},
  {hz:'慈悲',py:'cíbēi',en:'compassion',lvl:6},{hz:'功德',py:'gōngdé',en:'merit',lvl:6},
  {hz:'觉悟',py:'juéwù',en:'enlightenment/awakening',lvl:6},{hz:'因果',py:'yīnguǒ',en:'cause and effect',lvl:6},
  {hz:'轮回',py:'lúnhuí',en:'reincarnation',lvl:6},{hz:'誓愿',py:'shìyuàn',en:'vow',lvl:6},
  {hz:'劫难',py:'jiénàn',en:'ordeal',lvl:6},{hz:'磨炼',py:'móliàn',en:'tempering/trial',lvl:6},
  {hz:'幻境',py:'huànjìng',en:'illusion',lvl:7},{hz:'真身',py:'zhēnshēn',en:'true form',lvl:7},
  {hz:'心魔',py:'xīnmó',en:'inner demon',lvl:7},{hz:'贪念',py:'tānniàn',en:'greed/desire',lvl:7},
  {hz:'欲望',py:'yùwàng',en:'desire',lvl:7},{hz:'忍耐',py:'rěnnài',en:'endurance',lvl:7},
  {hz:'迷阵',py:'mízhèn',en:'illusion maze',lvl:7},{hz:'封印',py:'fēngyìn',en:'seal',lvl:7},
  {hz:'咒语',py:'zhòuyǔ',en:'spell/incantation',lvl:7},{hz:'仙丹',py:'xiāndān',en:'elixir',lvl:7},
  {hz:'芭蕉扇',py:'bājiāoshàn',en:'Plantain Fan',lvl:7},{hz:'金箍棒',py:'jīngūbàng',en:'Golden-Hooped Rod',lvl:7},
  {hz:'火焰山',py:'huǒyànshān',en:'Flaming Mountain',lvl:7},{hz:'盘丝洞',py:'pánsīdòng',en:'Spider Cave',lvl:7},
  {hz:'女儿国',py:'nǚérguó',en:'Woman Kingdom',lvl:7},{hz:'狮驼岭',py:'shītuólǐng',en:'Lion Camel Ridge',lvl:7},
  {hz:'真假',py:'zhēnjiǎ',en:'true and false',lvl:8},{hz:'善恶',py:'shàn\'è',en:'good and evil',lvl:8},
  {hz:'渡化',py:'dùhuà',en:'to redeem/save',lvl:8},{hz:'执念',py:'zhíniàn',en:'obsession',lvl:8},
  {hz:'试炼',py:'shìliàn',en:'trial',lvl:8},{hz:'圆满',py:'yuánmǎn',en:'fulfillment',lvl:8},
  {hz:'慧眼',py:'huìyǎn',en:'wise eye',lvl:8},{hz:'神通',py:'shéntōng',en:'divine power',lvl:8},
  {hz:'应劫',py:'yìngjié',en:'to meet one\'s destined trial',lvl:8},{hz:'归真',py:'guīzhēn',en:'to return to truth',lvl:8},
  {hz:'普度',py:'pǔdù',en:'to save all beings',lvl:8},{hz:'空门',py:'kōngmén',en:'the Buddhist path',lvl:8},
  {hz:'凡心',py:'fánxīn',en:'mortal desire',lvl:8},{hz:'佛心',py:'fóxīn',en:'Buddha-heart',lvl:8},
  {hz:'天命',py:'tiānmìng',en:'mandate of Heaven',lvl:9},{hz:'宿缘',py:'sùyuán',en:'destined bond',lvl:9},
  {hz:'顿悟',py:'dùnwù',en:'sudden enlightenment',lvl:9},{hz:'开示',py:'kāishì',en:'to instruct spiritually',lvl:9},
  {hz:'禅机',py:'chánjī',en:'Zen insight',lvl:9},{hz:'法相',py:'fǎxiàng',en:'sacred appearance',lvl:9},
  {hz:'无常',py:'wúcháng',en:'impermanence',lvl:9},{hz:'执着',py:'zhízhuó',en:'attachment',lvl:9},
  {hz:'显圣',py:'xiǎnshèng',en:'to manifest divinity',lvl:9},{hz:'证道',py:'zhèngdào',en:'to realize the Way',lvl:9},
  {hz:'灵台',py:'língtái',en:'spiritual mind',lvl:10},{hz:'玄妙',py:'xuánmiào',en:'mysterious and subtle',lvl:10},
  {hz:'般若',py:'bōrě',en:'prajna wisdom',lvl:10},{hz:'涅槃',py:'nièpán',en:'nirvana',lvl:10},
  {hz:'法界',py:'fǎjiè',en:'realm of Dharma',lvl:10},{hz:'化缘',py:'huàyuán',en:'to seek alms',lvl:10},
  {hz:'无量',py:'wúliàng',en:'boundless',lvl:10},{hz:'慈航',py:'cíháng',en:'boat of compassion',lvl:10},
  // Obstacle-trial vocabulary
  {hz:'过',py:'guò',en:'to pass through',lvl:3,tags:['build']},
  {hz:'渡',py:'dù',en:'to cross water',lvl:4,tags:['build']},
  {hz:'越',py:'yuè',en:'to cross over',lvl:4,tags:['build']},
  {hz:'破',py:'pò',en:'to break through',lvl:4,tags:['build']},
  {hz:'解',py:'jiě',en:'to untie/solve',lvl:4,tags:['build']},
  {hz:'借',py:'jiè',en:'to borrow',lvl:4,tags:['build']},
  {hz:'护',py:'hù',en:'to protect',lvl:4,tags:['build']},
  {hz:'救',py:'jiù',en:'to rescue',lvl:4,tags:['build']},
  {hz:'闯',py:'chuǎng',en:'to charge through',lvl:5,tags:['build']},
  {hz:'寻',py:'xún',en:'to search for',lvl:4,tags:['build']},
  {hz:'翻',py:'fān',en:'to turn over/cross',lvl:4,tags:['build']},
  {hz:'挡',py:'dǎng',en:'to block',lvl:4,tags:['build']},
  {hz:'险',py:'xiǎn',en:'dangerous',lvl:5,tags:['build']},
  {hz:'关卡',py:'guānqiǎ',en:'checkpoint/barrier',lvl:5,tags:['build']},
  {hz:'石桥',py:'shíqiáo',en:'stone bridge',lvl:5,tags:['build']},
  {hz:'渡船',py:'dùchuán',en:'ferry boat',lvl:5,tags:['build']},
  {hz:'山门',py:'shānmén',en:'mountain gate',lvl:5,tags:['build']},
  {hz:'迷路',py:'mílù',en:'to lose the way',lvl:5,tags:['build']},
  {hz:'指路',py:'zhǐlù',en:'to show the way',lvl:5,tags:['build']},
  {hz:'启程',py:'qǐchéng',en:'to set out',lvl:5,tags:['build']},
  // Temptation-trial vocabulary
  {hz:'宴',py:'yàn',en:'banquet',lvl:4,tags:['feast']},
  {hz:'酒',py:'jiǔ',en:'wine',lvl:4,tags:['feast']},
  {hz:'茶',py:'chá',en:'tea',lvl:3,tags:['feast']},
  {hz:'桃',py:'táo',en:'peach',lvl:4,tags:['feast']},
  {hz:'果',py:'guǒ',en:'fruit',lvl:3,tags:['feast']},
  {hz:'香',py:'xiāng',en:'fragrance',lvl:3,tags:['feast']},
  {hz:'梦',py:'mèng',en:'dream',lvl:4,tags:['feast']},
  {hz:'财',py:'cái',en:'wealth',lvl:5,tags:['feast']},
  {hz:'色',py:'sè',en:'beauty/desire',lvl:5,tags:['feast']},
  {hz:'欲',py:'yù',en:'desire',lvl:5,tags:['feast']},
  {hz:'骗',py:'piàn',en:'to deceive',lvl:4,tags:['feast']},
  {hz:'假象',py:'jiǎxiàng',en:'false appearance',lvl:5,tags:['feast']},
  {hz:'迷香',py:'míxiāng',en:'bewitching scent',lvl:5,tags:['feast']},
  {hz:'金银',py:'jīnyín',en:'gold and silver',lvl:5,tags:['feast']},
  {hz:'珍宝',py:'zhēnbǎo',en:'rare treasure',lvl:5,tags:['feast']},
  {hz:'王宴',py:'wángyàn',en:'royal feast',lvl:5,tags:['feast']},
  {hz:'仙桃',py:'xiāntáo',en:'immortal peach',lvl:5,tags:['feast']},
  {hz:'美梦',py:'měimèng',en:'sweet dream',lvl:5,tags:['feast']},
  {hz:'幻象',py:'huànxiàng',en:'illusion',lvl:5,tags:['feast']},
  {hz:'享乐',py:'xiǎnglè',en:'to indulge in pleasure',lvl:6,tags:['feast']},
];