const MP3_TRACKS = {
  mainscreen: 'sounds/mainscreen.mp3',
  map:        'sounds/map.mp3',
  battle:     'sounds/battle.mp3',
  feast:      'sounds/feast.mp3',
  activity:   'sounds/activity.mp3',
  victory:    'sounds/victory.mp3',
};
const MP3_TRACK_LABELS = {
  mainscreen: { zh:'长安发愿', en:'Vow at Chang\'an' },
  map:        { zh:'西行古道', en:'Road to the West' },
  battle:     { zh:'降妖鼓阵', en:'Demon-Quelling Drums' },
  feast:      { zh:'幻宴迷香', en:'Perfumed Hall of Temptation' },
  activity:   { zh:'涉险破关', en:'Crossing the Ordeal Gate' },
  victory:    { zh:'灵山功成', en:'Merit at Thunderclap' },
};

const ALL_HEROES = [
  {key:'sanzang', name:'唐三藏', nameEn:'Tang Sanzang', maxHp:5, desc:'Compassion Sutra',
   zh:'唐三藏即玄奘法师，受唐王之命西行求取真经。他慈悲坚忍，逢难不退，虽常陷险境，却始终以慈心感化同伴，维系取经队伍向西而行。',
   en:'Tang Sanzang, inspired by the monk Xuanzang, leads the pilgrimage west in search of the true scriptures. Compassionate and unwavering, he holds the company together through every trial.'},
  {key:'wukong', name:'孙悟空', nameEn:'Sun Wukong', maxHp:8, desc:'Ruyi Jingu Bang',
   zh:'孙悟空乃花果山石猴，通变化、会筋斗、使如意金箍棒。大闹天宫后被压五行山下，后拜唐僧为师，成为取经路上最锋利也最难驯的护法。',
   en:'Sun Wukong, the Stone Monkey of Flower-Fruit Mountain, commands transformations, cloud-leaps, and the Ruyi Jingu Bang. After his rebellion in Heaven, he becomes the pilgrimage\'s fiercest protector.'},
  {key:'bajie', name:'猪八戒', nameEn:'Zhu Bajie', maxHp:9, desc:'Nine-Toothed Rake',
   zh:'猪八戒原是天蓬元帅，因犯错被贬下界，化作猪形。贪吃好睡又爱抱怨，却在危急之时总肯挺身而出，是队伍里最有人情味的同伴。',
   en:'Zhu Bajie, once Marshal Tianpeng, fell from Heaven and took on a pig-like form. Gluttonous and comic, he still proves dependable when the road turns dangerous.'},
  {key:'wujing', name:'沙悟净', nameEn:'Sha Wujing', maxHp:7, desc:'Crescent Spade',
   zh:'沙悟净曾是卷帘大将，因触犯天条被贬流沙河。拜入唐僧门下后，他沉稳寡言，负重前行，是队伍里最可靠的守护者。',
   en:'Sha Wujing, once a heavenly curtain-bearing general, was exiled to the Flowing Sands. Quiet and steady, he becomes the group\'s anchor and shield.'},
  {key:'whitehorse', name:'白龙马', nameEn:'White Dragon Horse', maxHp:6, desc:'Cloud-Step Gallop',
   zh:'白龙马本是西海龙王三太子，因罪受罚，后化作唐僧坐骑。它沉默忠诚，踏云涉水，护送师父穿越千山万险。',
   en:'The White Dragon Horse is the Dragon King\'s third son, redeemed through service as Sanzang\'s mount. Swift and loyal, he carries the pilgrimage onward through impossible terrain.'},
  {key:'guanyin', name:'观音', nameEn:'Guanyin', maxHp:6, desc:'Lotus Mercy',
   zh:'观音菩萨奉佛祖之命安排取经大业，点化悟空、八戒、悟净与白龙马，使原本桀骜不驯的众生归入正道。',
   en:'Guanyin, the Bodhisattva of Compassion, sets the pilgrimage in motion and gathers its unlikely protectors into a single sacred mission.'},
  {key:'nezha', name:'哪吒', nameEn:'Nezha', maxHp:7, desc:'Wind-Fire Wheels',
   zh:'哪吒三太子身负风火轮与火尖枪，年少而神通广大。天庭与妖魔交锋之时，他常是最先赶到的神将。',
   en:'Nezha, the youthful warrior-god with Wind-Fire Wheels, brings explosive speed and divine force whenever Heaven intervenes on the road.'},
  {key:'erlang', name:'二郎神', nameEn:'Erlang Shen', maxHp:8, desc:'Heaven-Hound Glaive',
   zh:'二郎神法力高强，额生天眼，能辨真假变化。他既是孙悟空最难缠的旧敌之一，也是西行途中衡量神通高下的标尺。',
   en:'Erlang Shen, wielder of the heavenly eye, sees through disguise and illusion. He embodies disciplined celestial power at the edge of Wukong\'s wild brilliance.'},
];

const CHAPTER_ART = {};

const STORY_CHAPTERS = [
  { id:'c1', unlockAt:1, illus:'🪨', title:'石猴出世', titleEn:'Birth of the Stone Monkey',
    zh:'花果山巅，一块仙石受日月精华孕育，忽然迸裂，生出石猴。它无父无母，却胆气过人，从此开启了一段惊动三界的传奇。',
    en:'On Flower-Fruit Mountain, a magic stone split open under the power of Heaven and Earth, giving birth to the Stone Monkey. Fearless from the very beginning, he was destined to shake the Three Realms.' },
  { id:'c2', unlockAt:4, illus:'🏯', title:'大闹天宫', titleEn:'Havoc in Heaven',
    zh:'孙悟空偷仙桃、饮御酒、闯天宫，自号齐天大圣。十万天兵难制其锋，直到如来佛祖出手，才将他压在五行山下。',
    en:'Sun Wukong stole peaches, drank immortal wine, and defied Heaven itself. Only the Buddha could finally subdue him beneath Five Elements Mountain.' },
  { id:'c3', unlockAt:8, illus:'⛰️', title:'五行山下', titleEn:'Beneath Five Elements Mountain',
    zh:'五百年后，观音点化唐僧西行。唐僧揭去佛帖，放出悟空，也让这个桀骜不驯的猴王第一次背负起护法的责任。',
    en:'Five hundred years later, Tang Sanzang freed Wukong from the mountain. The wild Monkey King gained not only freedom, but a sacred duty.' },
  { id:'c4', unlockAt:12, illus:'🐉', title:'西行收徒', titleEn:'Gathering the Pilgrims',
    zh:'白龙马、猪八戒、沙悟净先后加入队伍。原本各有罪业的妖与神，逐渐在西行路上学会守护、克制与同行。',
    en:'The White Dragon Horse, Zhu Bajie, and Sha Wujing joined the journey one by one. The pilgrimage slowly turned former sinners into true companions.' },
  { id:'c5', unlockAt:16, illus:'💀', title:'三打白骨精', titleEn:'Three Battles with the White Bone Demon',
    zh:'白骨精三次化作凡人欺骗唐僧，只为吃上一口唐僧肉。悟空三次识破妖身，却也因此被误解逐走，忠心反成孤证。',
    en:'The White Bone Demon disguised herself three times to deceive Sanzang. Wukong alone saw through the trick, yet his loyalty was mistaken for cruelty.' },
  { id:'c6', unlockAt:20, illus:'⚡', title:'车迟斗法', titleEn:'Contest of Magic at Cart Slow Kingdom',
    zh:'车迟国三大仙仗势欺僧，逼得佛门凋敝。悟空师兄弟与其比法、比雨、比变化，以智慧与神通替僧众雪耻。',
    en:'At Cart Slow Kingdom, false immortals oppressed the monks. Wukong and his brothers defeated them in contests of rain, magic, and wit.' },
  { id:'c7', unlockAt:24, illus:'👑', title:'女儿国', titleEn:'The Woman Kingdom',
    zh:'女儿国一段情意最难。国王真心挽留唐僧，而唐僧只能向西。此难无刀无火，却最见凡心与佛心的拉扯。',
    en:'In the Woman Kingdom, no demon blade was sharper than affection itself. The Queen offered love, but Sanzang could only continue westward.' },
  { id:'c8', unlockAt:28, illus:'🔥', title:'火云洞', titleEn:'The Fire Cloud Cave',
    zh:'红孩儿会三昧真火，连悟空也难近身。观音最终以慈悲降伏顽童，将一场烈焰之灾化作新的度化。',
    en:'Red Boy\'s Samadhi Fire nearly defeated the pilgrims. Guanyin turned a blazing disaster into an act of salvation.' },
  { id:'c9', unlockAt:32, illus:'🕸️', title:'盘丝洞', titleEn:'Spider Cave',
    zh:'盘丝洞七蜘蛛精以美色、毒丝与陷阱困住师徒。西行路上，许多妖怪都不是直来直去的恶，而是精巧又危险的诱惑。',
    en:'In Spider Cave, seven spider demons used beauty, poison, and webs to ensnare the pilgrims. Temptation proved every bit as deadly as brute force.' },
  { id:'c10', unlockAt:36, illus:'🦅', title:'狮驼岭', titleEn:'Lion Camel Ridge',
    zh:'狮驼岭群妖盘踞，青狮、白象、大鹏层层设伏，堪称西行路上最凶险的一段。纵有神通，也需耐心与协力才能脱身。',
    en:'Lion Camel Ridge brought the pilgrims into one of their darkest trials, where monstrous kings ruled a whole mountain of terror.' },
  { id:'c11', unlockAt:40, illus:'🌋', title:'火焰山', titleEn:'Flaming Mountain',
    zh:'火焰山烈火千里，非芭蕉扇不能熄。悟空为借宝扇，与铁扇公主、牛魔王斗智斗勇，方为师父开出西进之路。',
    en:'The Flaming Mountain could only be crossed with the Plantain Fan. Wukong had to outwit Iron Fan Princess and Bull Demon King to clear the road.' },
  { id:'c12', unlockAt:48, illus:'📜', title:'雷音真经', titleEn:'The True Scriptures at Thunderclap',
    zh:'历经九九八十一难，师徒终于抵达灵山雷音寺。真经并非只在经卷之中，更在一路上所修得的慈悲、忍耐与觉悟。',
    en:'After eighty-one ordeals, the pilgrims reached Thunderclap Monastery. The truest scripture lay not only in the scrolls, but in the virtues forged along the road.' },
];

const PROVINCE_STORIES = {
  0:  { zh:'长安是大愿的起点。玄奘在此领下诏命，也从此把一条官道走成了修心之路。', en:'Chang\'an is the point where imperial duty becomes sacred pilgrimage, and the road west first takes shape.' },
  1:  { zh:'洪福寺中，出发前的平静像最后一口长安的气息。真正的艰难，往往开始在誓愿说出口之后。', en:'At Hongfu Temple, the calm before departure marks the moment when a vow becomes harder to abandon.' },
  2:  { zh:'两界山分开凡俗与神怪，也分开旧日的安稳与未来的劫难。过了此山，世界便不再按常理回应。', en:'Two Worlds Mountain divides the ordinary world from the realm of spirits, portents, and ordeal.' },
  3:  { zh:'猎户庄里的人间勇气，替取经路开了第一道门。西行并不只靠神佛，也靠凡人愿意护送善念一程。', en:'Hunter Liu shows that the pilgrimage depends not only on gods and demons, but on ordinary human courage.' },
  4:  { zh:'五行山下压着孙悟空，也压着他昔日无法无天的旧性。揭去佛帖，不只是放出猴王，更是放出一场新的考验。', en:'Releasing Wukong from Five Elements Mountain frees both the Monkey King and the dangerous force he still carries within him.' },
  5:  { zh:'蛇盘山的曲折山路像是在先教人收心。西行不是一跃而成，而是每一步都学着把锋芒放稳。', en:'Serpent-Coil Mountain teaches that the road west is not won in one leap, but by steadying the heart step by step.' },
  6:  { zh:'鹰愁涧波深崖险，白龙伏于其下。龙子化马之后，队伍第一次真正有了向西行进的形体。', en:'At Eagle Grief Ravine, the dragon prince becomes the White Dragon Horse and gives the pilgrimage its forward motion.' },
  7:  { zh:'观音禅院中，一件袈裟便能照出贪心。修行人若看不破宝物，也会在自己院门里迷失。', en:'At Guanyin Monastery, a single robe exposes how greed can flourish even in a place of worship.' },
  8:  { zh:'黑风山的黑熊精夺走袈裟，让人明白护法之物也会引来觊觎。宝物从来不只考验敌人，也考验持有它的人。', en:'Black Wind Mountain shows that sacred objects attract danger, and that treasure tests its keepers as much as its thieves.' },
  9:  { zh:'高老庄像是人间琐事，却藏着猪八戒的前缘。越是寻常的地方，越可能住着未被点化的命数。', en:'Gao Village hides Zhu Bajie in the middle of ordinary life, proving that destiny often waits inside the commonplace.' },
  10: { zh:'福陵山不是英雄登场，而是旧罪回头。八戒加入之后，队伍第一次有了笨拙却真实的人情味。', en:'At Fuling Mountain, Bajie turns from fallen marshal to flawed companion, adding warmth as well as trouble to the journey.' },
  11: { zh:'黄风岭妖风大作，连火眼金睛也会一时失灵。并非每一场劫难都能靠蛮力取胜。', en:'Yellow Wind Ridge proves that vision, power, and confidence can all be stripped away by the right enemy.' },
  12: { zh:'流沙河曾吞没无数性命，沙悟净却在此等到归途。恶水一旦被度化，也能成为真正的渡口。', en:'The Flowing Sands turn from a place of death into a crossing once Sha Wujing is redeemed.' },
  13: { zh:'骷髅山荒冢累累，还未见白骨精，气息已先逼人心寒。很多劫难在露出真身之前，就先以阴影试人。', en:'Skeleton Mountain frightens long before its demon appears, reminding the pilgrims that dread often arrives before danger takes form.' },
  14: { zh:'万寿山的人参果，看似是仙缘，实则是对分寸的考验。越珍贵的东西，越能照出人心的急躁。', en:'At Wanshou Mountain, the ginseng fruit looks like a blessing, but it really tests restraint.' },
  15: { zh:'五庄观不是一场单纯争斗，而是一堂赔罪的功课。取经路上，认错与补过有时比战胜妖怪更难。', en:'Five Manor Abbey teaches that making amends can be a greater trial than defeating a monster.' },
  16: { zh:'白虎岭上，白骨精三次化形欺人。最险的敌人不是最凶恶，而是最像善良与可怜。', en:'On White Tiger Ridge, the White Bone Demon shows that the deadliest foe is the one who looks harmless.' },
  17: { zh:'宝象国的失序牵扯王室、妖怪与离散之苦。一个王国的混乱，也能成为一面照见人心的镜子。', en:'Baoxiang Kingdom turns royal sorrow and demonic intrusion into a mirror for fear, grief, and attachment.' },
  18: { zh:'波月洞里，黄袍怪把欲望与幻象织在一起。妖怪若披上情意，往往比刀兵更难识破。', en:'Moon-Wave Cave reveals how desire and illusion can be more dangerous than a direct assault.' },
  19: { zh:'平顶山上，金角大王法宝层出不穷。神通再大，也要靠机变去拆穿一重又一重的布局。', en:'Flat-Top Mountain turns the battle into a contest of wit, where treasures and traps stack one atop another.' },
  20: { zh:'莲花洞延续着金银角的法宝之难。真正的压力不在一件法器，而在敌人总有下一层算计。', en:'Lotus Flower Cave extends the crisis by showing that the real threat is not one artifact, but endless schemes.' },
  21: { zh:'乌鸡国井底沉冤，说明西行不只是降妖，也常是替世间扶正。冤屈若不见天日，人间本身便会像妖境。', en:'Crow-Cock Kingdom shows that some of the road west is spent correcting human injustice rather than fighting demons.' },
  22: { zh:'枯松涧的干风与焦气，先替火云洞投下前兆。大灾到来之前，天地往往已先改了颜色。', en:'Dry Pine Ravine foreshadows the Fire Cloud ordeal, when the world itself seems to take on the taste of smoke.' },
  23: { zh:'火云洞中，红孩儿的三昧真火烧得连悟空也难近身。最顽劣的敌人，最后却也可能成为可度化的众生。', en:'In Fire Cloud Cave, Red Boy nearly overwhelms the pilgrims, yet even he can be turned toward a different fate.' },
  24: { zh:'车迟国里，假仙人仗势欺僧，把法术当作压人的外衣。悟空师兄弟赢下的不只是斗法，更是真伪之辨。', en:'Cart Slow Kingdom makes the pilgrims prove that spectacle and arrogance are not the same as true cultivation.' },
  25: { zh:'通天河又冷又深，妖王还借祭祀勒索百姓。过河之前，先要让众人相信恐惧不是天命。', en:'At the River of Heaven, the pilgrims must defeat fear among the people before they can cross the water itself.' },
  26: { zh:'金兜山的青牛精凭一个金刚圈便让神兵失色。遇到这种敌人，蛮力越大，反而越显得无用。', en:'Golden Pocket Mountain pits the pilgrims against a foe whose single ring can humble strength and weapons alike.' },
  27: { zh:'女儿国最难的不是脱身，而是拒绝温柔。这里没有烈火刀兵，却最逼人直视凡心。', en:'The Woman Kingdom offers tenderness instead of violence, making it one of the hardest tests on the whole road.' },
  28: { zh:'子母河的怪泉提醒众人，肉身也会成为劫难的一部分。哪怕神通在身，也逃不过病厄与疲惫。', en:'The Mother-and-Child River reminds the pilgrims that even a sacred journey must still pass through bodily weakness.' },
  29: { zh:'解阳山的一口泉，成了众人续行的关键。很多时候，西行不是向前争胜，而是先学会求助。', en:'At Jiyang Mountain, survival depends not on victory, but on finding the one thing needed to continue.' },
  30: { zh:'毒敌山的蝎子精，以一根毒尾便让神佛也皱眉。越阴狠的敌人，越会把胜负藏在最细小的一击里。', en:'Poison-Enemy Mountain shows that one venomous strike can matter more than a whole army of lesser threats.' },
  31: { zh:'火焰山把西行正路彻底封住，像是告诉众人，志向并不天然能开山辟路。前进，有时必须先借来一阵风。', en:'Flaming Mountain blocks the road so completely that purpose alone is not enough; the pilgrims need another power to move on.' },
  32: { zh:'翠云山一借芭蕉扇，借的不只是法宝，也是一段旧怨旧情。神怪之间的关系，往往比战斗本身更难理清。', en:'Green Cloud Mountain turns the search for the Plantain Fan into a negotiation tangled with old loyalties and resentment.' },
  33: { zh:'积雷山见到牛魔王，便是把旧识、旧力与旧胜负都重新翻起。走到这里，悟空也必须面对自己早年的影子。', en:'Jilei Mountain forces Wukong to confront an old equal, where past glory and present duty collide.' },
  34: { zh:'祭赛国的舍利失窃，让国中光明一度断绝。圣物若被污损，人心往往比塔灯更快暗下去。', en:'In Sacrifice Kingdom, the theft of a relic darkens both the temple and the spirits of the people.' },
  35: { zh:'金光寺重燃塔灯，不只是找回宝物，更是替一座寺院找回庄严。西行也常要替别人的信心续火。', en:'Golden Light Temple shows that restoring faith can matter as much as recovering the lost treasure itself.' },
  36: { zh:'小雷音最险在于它像真的。假佛若披上庄严外相，连修行之人也可能在敬畏中失足。', en:'Small Thunderclap is dangerous because it looks holy, turning reverence itself into a trap.' },
  37: { zh:'七绝山泥泞闭塞，连路都像被劫难泡软了。不是每一关都有妖王，有时单是前路难行就足够折磨人。', en:'Seven-Extinction Mountain proves that terrain alone can become a torment when the road itself turns against the travelers.' },
  38: { zh:'朱紫国王病重，悟空等人在此先行医再行法。救人之心若不在，降妖也会失了分寸。', en:'At Scarlet Purple Kingdom, healing comes before combat, and compassion sets the measure for what follows.' },
  39: { zh:'麒麟山赛太岁掳走王后，把权势与私欲织成一张网。西行一路所破的，从来不只是妖身，也是妄念。', en:'Qilin Mountain binds royal power and selfish desire together, showing how obsession can wear many forms.' },
  40: { zh:'盘丝洞里，蜘蛛精以美色、毒丝与温语一齐设伏。越像盛情招待的地方，越要小心是不是罗网。', en:'Spider Cave wraps its trap in beauty and hospitality, making temptation feel almost welcoming.' },
  41: { zh:'黄花观的百眼魔君以毒茶与金光迷人神智。真正的凶险，有时不是猛攻，而是让人慢慢失去判断。', en:'Yellow Flower Monastery weakens the pilgrims by clouding judgment, proving that confusion can be as deadly as force.' },
  42: { zh:'狮驼岭是群妖并立的地狱关口，青狮、白象、大鹏层层相逼。这里几乎把西行推到了最险的边缘。', en:'Lion Camel Ridge gathers multiple monstrous kings into one of the darkest, most punishing stretches of the journey.' },
  43: { zh:'比丘国以童子续命，看似礼法井然，实则邪术横流。最令人心惊的，从来不是混乱，而是恶能被包装成秩序。', en:'Bhikshu Kingdom shows how horror becomes worse when cruelty hides behind ritual and order.' },
  44: { zh:'无底洞深不见底，地涌夫人把贪恋与占有拉入地下。越往深处走，越像是在照见不肯放手的执念。', en:'Bottomless Cave turns possession and desire into a descent, where obsession itself becomes the labyrinth.' },
  45: { zh:'玉华州的少年王子敬仰悟空师兄弟，让沉重的路途短暂有了轻快。可这一点光亮，也是在提醒众人已走得多远。', en:'Jade Flower Prefecture offers a brief warmth of admiration and hope, making the long pilgrimage feel human again.' },
  46: { zh:'那烂陀已近佛土，空气都像变得庄严。走到这里，师徒几人早已不是最初离开长安时的模样。', en:'Nalanda stands near the Buddhist heartlands, where the pilgrims can finally feel how much the road has changed them.' },
  47: { zh:'雷音寺终现云间，真经近在眼前。可真正被带到此处的，不只是脚步，更是一路磨出的慈悲、忍耐与觉悟。', en:'Thunderclap Monastery marks the end of the road, but the true scripture is also the compassion, endurance, and insight forged along the way.' },
};