const MP3_TRACKS = {
  mainscreen: 'sounds/mainscreen.mp3',
  map:        'sounds/map.mp3',
  battle:     'sounds/battle.mp3',
  feast:      'sounds/feast.mp3',
  activity:   'sounds/activity.mp3',
  victory:    'sounds/victory.mp3',
};
const MP3_TRACK_LABELS = {
  mainscreen: { zh:'长安发愿', en:'Vow at Chang\'an' },
  map:        { zh:'西行古道', en:'Road to the West' },
  battle:     { zh:'降妖鼓阵', en:'Demon-Quelling Drums' },
  feast:      { zh:'幻宴迷香', en:'Perfumed Hall of Temptation' },
  activity:   { zh:'涉险破关', en:'Crossing the Ordeal Gate' },
  victory:    { zh:'灵山功成', en:'Merit at Thunderclap' },
};

const ALL_HEROES = [
  {key:'sanzang', name:'唐三藏', nameEn:'Tang Sanzang', maxHp:5, desc:'Compassion Sutra',
   zh:'唐三藏即玄奘法师，受唐王之命西行求取真经。他慈悲坚忍，逢难不退，虽常陷险境，却始终以慈心感化同伴，维系取经队伍向西而行。',
   en:'Tang Sanzang, inspired by the monk Xuanzang, leads the pilgrimage west in search of the true scriptures. Compassionate and unwavering, he holds the company together through every trial.'},
  {key:'wukong', name:'孙悟空', nameEn:'Sun Wukong', maxHp:8, desc:'Ruyi Jingu Bang',
   zh:'孙悟空乃花果山石猴，通变化、会筋斗、使如意金箍棒。大闹天宫后被压五行山下，后拜唐僧为师，成为取经路上最锋利也最难驯的护法。',
   en:'Sun Wukong, the Stone Monkey of Flower-Fruit Mountain, commands transformations, cloud-leaps, and the Ruyi Jingu Bang. After his rebellion in Heaven, he becomes the pilgrimage\'s fiercest protector.'},
  {key:'bajie', name:'猪八戒', nameEn:'Zhu Bajie', maxHp:9, desc:'Nine-Toothed Rake',
   zh:'猪八戒原是天蓬元帅，因犯错被贬下界，化作猪形。贪吃好睡又爱抱怨，却在危急之时总肯挺身而出，是队伍里最有人情味的同伴。',
   en:'Zhu Bajie, once Marshal Tianpeng, fell from Heaven and took on a pig-like form. Gluttonous and comic, he still proves dependable when the road turns dangerous.'},
  {key:'wujing', name:'沙悟净', nameEn:'Sha Wujing', maxHp:7, desc:'Crescent Spade',
   zh:'沙悟净曾是卷帘大将，因触犯天条被贬流沙河。拜入唐僧门下后，他沉稳寡言，负重前行，是队伍里最可靠的守护者。',
   en:'Sha Wujing, once a heavenly curtain-bearing general, was exiled to the Flowing Sands. Quiet and steady, he becomes the group\'s anchor and shield.'},
  {key:'whitehorse', name:'白龙马', nameEn:'White Dragon Horse', maxHp:6, desc:'Cloud-Step Gallop',
   zh:'白龙马本是西海龙王三太子，因罪受罚，后化作唐僧坐骑。它沉默忠诚，踏云涉水，护送师父穿越千山万险。',
   en:'The White Dragon Horse is the Dragon King\'s third son, redeemed through service as Sanzang\'s mount. Swift and loyal, he carries the pilgrimage onward through impossible terrain.'},
  {key:'guanyin', name:'观音', nameEn:'Guanyin', maxHp:6, desc:'Lotus Mercy',
   zh:'观音菩萨奉佛祖之命安排取经大业，点化悟空、八戒、悟净与白龙马，使原本桀骜不驯的众生归入正道。',
   en:'Guanyin, the Bodhisattva of Compassion, sets the pilgrimage in motion and gathers its unlikely protectors into a single sacred mission.'},
  {key:'nezha', name:'哪吒', nameEn:'Nezha', maxHp:7, desc:'Wind-Fire Wheels',
   zh:'哪吒三太子身负风火轮与火尖枪，年少而神通广大。天庭与妖魔交锋之时，他常是最先赶到的神将。',
   en:'Nezha, the youthful warrior-god with Wind-Fire Wheels, brings explosive speed and divine force whenever Heaven intervenes on the road.'},
  {key:'erlang', name:'二郎神', nameEn:'Erlang Shen', maxHp:8, desc:'Heaven-Hound Glaive',
   zh:'二郎神法力高强，额生天眼，能辨真假变化。他既是孙悟空最难缠的旧敌之一，也是西行途中衡量神通高下的标尺。',
   en:'Erlang Shen, wielder of the heavenly eye, sees through disguise and illusion. He embodies disciplined celestial power at the edge of Wukong\'s wild brilliance.'},
];

const CHAPTER_ART = {};

const STORY_CHAPTERS = [
  { id:'c1', unlockAt:1, illus:'🪨', title:'石猴出世', titleEn:'Birth of the Stone Monkey',
    zh:'花果山巅，一块仙石受日月精华孕育，忽然迸裂，生出石猴。它无父无母，却胆气过人，从此开启了一段惊动三界的传奇。',
    en:'On Flower-Fruit Mountain, a magic stone split open under the power of Heaven and Earth, giving birth to the Stone Monkey. Fearless from the very beginning, he was destined to shake the Three Realms.' },
  { id:'c2', unlockAt:2, illus:'🏯', title:'大闹天宫', titleEn:'Havoc in Heaven',
    zh:'孙悟空偷仙桃、饮御酒、闯天宫，自号齐天大圣。十万天兵难制其锋，直到如来佛祖出手，才将他压在五行山下。',
    en:'Sun Wukong stole peaches, drank immortal wine, and defied Heaven itself. Only the Buddha could finally subdue him beneath Five Elements Mountain.' },
  { id:'c3', unlockAt:4, illus:'⛰️', title:'五行山下', titleEn:'Beneath Five Elements Mountain',
    zh:'五百年后，观音点化唐僧西行。唐僧揭去佛帖，放出悟空，也让这个桀骜不驯的猴王第一次背负起护法的责任。',
    en:'Five hundred years later, Tang Sanzang freed Wukong from the mountain. The wild Monkey King gained not only freedom, but a sacred duty.' },
  { id:'c4', unlockAt:6, illus:'🐉', title:'西行收徒', titleEn:'Gathering the Pilgrims',
    zh:'白龙马、猪八戒、沙悟净先后加入队伍。原本各有罪业的妖与神，逐渐在西行路上学会守护、克制与同行。',
    en:'The White Dragon Horse, Zhu Bajie, and Sha Wujing joined the journey one by one. The pilgrimage slowly turned former sinners into true companions.' },
  { id:'c5', unlockAt:8, illus:'💀', title:'三打白骨精', titleEn:'Three Battles with the White Bone Demon',
    zh:'白骨精三次化作凡人欺骗唐僧，只为吃上一口唐僧肉。悟空三次识破妖身，却也因此被误解逐走，忠心反成孤证。',
    en:'The White Bone Demon disguised herself three times to deceive Sanzang. Wukong alone saw through the trick, yet his loyalty was mistaken for cruelty.' },
  { id:'c6', unlockAt:10, illus:'⚡', title:'车迟斗法', titleEn:'Contest of Magic at Cart Slow Kingdom',
    zh:'车迟国三大仙仗势欺僧，逼得佛门凋敝。悟空师兄弟与其比法、比雨、比变化，以智慧与神通替僧众雪耻。',
    en:'At Cart Slow Kingdom, false immortals oppressed the monks. Wukong and his brothers defeated them in contests of rain, magic, and wit.' },
  { id:'c7', unlockAt:12, illus:'👑', title:'女儿国', titleEn:'The Woman Kingdom',
    zh:'女儿国一段情意最难。国王真心挽留唐僧，而唐僧只能向西。此难无刀无火，却最见凡心与佛心的拉扯。',
    en:'In the Woman Kingdom, no demon blade was sharper than affection itself. The Queen offered love, but Sanzang could only continue westward.' },
  { id:'c8', unlockAt:14, illus:'🔥', title:'火云洞', titleEn:'The Fire Cloud Cave',
    zh:'红孩儿会三昧真火，连悟空也难近身。观音最终以慈悲降伏顽童，将一场烈焰之灾化作新的度化。',
    en:'Red Boy\'s Samadhi Fire nearly defeated the pilgrims. Guanyin turned a blazing disaster into an act of salvation.' },
  { id:'c9', unlockAt:16, illus:'🕸️', title:'盘丝洞', titleEn:'Spider Cave',
    zh:'盘丝洞七蜘蛛精以美色、毒丝与陷阱困住师徒。西行路上，许多妖怪都不是直来直去的恶，而是精巧又危险的诱惑。',
    en:'In Spider Cave, seven spider demons used beauty, poison, and webs to ensnare the pilgrims. Temptation proved every bit as deadly as brute force.' },
  { id:'c10', unlockAt:18, illus:'🦅', title:'狮驼岭', titleEn:'Lion Camel Ridge',
    zh:'狮驼岭群妖盘踞，青狮、白象、大鹏层层设伏，堪称西行路上最凶险的一段。纵有神通，也需耐心与协力才能脱身。',
    en:'Lion Camel Ridge brought the pilgrims into one of their darkest trials, where monstrous kings ruled a whole mountain of terror.' },
  { id:'c11', unlockAt:20, illus:'🌋', title:'火焰山', titleEn:'Flaming Mountain',
    zh:'火焰山烈火千里，非芭蕉扇不能熄。悟空为借宝扇，与铁扇公主、牛魔王斗智斗勇，方为师父开出西进之路。',
    en:'The Flaming Mountain could only be crossed with the Plantain Fan. Wukong had to outwit Iron Fan Princess and Bull Demon King to clear the road.' },
  { id:'c12', unlockAt:24, illus:'📜', title:'雷音真经', titleEn:'The True Scriptures at Thunderclap',
    zh:'历经九九八十一难，师徒终于抵达灵山雷音寺。真经并非只在经卷之中，更在一路上所修得的慈悲、忍耐与觉悟。',
    en:'After eighty-one ordeals, the pilgrims reached Thunderclap Monastery. The truest scripture lay not only in the scrolls, but in the virtues forged along the road.' },
];

const PROVINCE_STORIES = {
  0:  { zh:'长安是大唐都城，也是取经大愿出发的地方。从这里开始，路不再只是官道，而是通向心性与觉悟的长程。', en:'Chang\'an is the imperial capital and the true beginning of the pilgrimage. From here, the road leads not just west, but inward.' },
  1:  { zh:'两界山是凡俗与神怪的分界。踏过此山，唐僧再也不能以寻常世情来衡量路上的一切。', en:'Two Worlds Mountain marks the threshold between ordinary travel and the realm of spirits, monsters, and destiny.' },
  2:  { zh:'五行山下压着昔日大闹天宫的孙悟空。佛帖一揭，取经路便有了最锋利的护法，也有了最难驯的考验。', en:'Beneath Five Elements Mountain waits Sun Wukong, once rebel of Heaven. Freeing him gives the mission its greatest weapon and its greatest risk.' },
  3:  { zh:'鹰愁涧波急崖深，白龙伏水其间。龙子悔罪化马，取经之路自此真正成行。', en:'At Eagle Grief Ravine, the dragon prince is redeemed and becomes the White Dragon Horse, allowing the journey to truly begin.' },
  4:  { zh:'高老庄看似寻常村庄，却藏着猪八戒的前缘。一个贪吃懒惰的妖，竟也能在佛门里学会担当。', en:'Gao Village hides the story of Zhu Bajie, proving that even the flawed and comic may be transformed into companions.' },
  5:  { zh:'黄风岭妖风遮天，连悟空的火眼金睛也一度失势。西行路上的敌人，不总靠力气取胜。', en:'On Yellow Wind Ridge, blinding demon winds show that brute force alone cannot solve every ordeal.' },
  6:  { zh:'流沙河吞人无数，沙悟净独守其岸。直到归入取经队伍，这片恶水才第一次成为渡口而非绝境。', en:'The Flowing Sands was once a place of death. With Sha Wujing\'s redemption, it becomes a crossing instead of a grave.' },
  7:  { zh:'万寿山五庄观有镇元子与人参果。真正的修行，不只在战胜妖怪，也在学会为过错负责。', en:'At Wanshou Mountain and the Five Manor Abbey, the pilgrims learn that cultivation also means making amends for one\'s mistakes.' },
  8:  { zh:'白虎岭上白骨精三次变形，只为骗取唐僧信任。最难的敌人，往往不是最凶，而是最像善人。', en:'On White Tiger Ridge, the White Bone Demon proves that the most dangerous foes are often the most convincing pretenders.' },
  9:  { zh:'宝象国的劫难牵扯妖怪、国王与公主，真假恩怨交织。西行路上，每一国都像一面照人心的镜子。', en:'Baoxiang Kingdom entangles monsters, royals, and deception, turning a kingdom into a mirror for human desire and fear.' },
  10: { zh:'平顶山金角银角法宝层出不穷，连悟空也需以机变取胜。神通广大，有时还不如一句机灵话。', en:'At Flat-Top Mountain, magical treasures nearly overwhelm the pilgrims. Cleverness becomes stronger than raw power.' },
  11: { zh:'乌鸡国冤魂难雪，井底旧案未平。取经并不总是与妖魔厮杀，也常是替世间伸冤扶正。', en:'In Crow-Cock Kingdom, the pilgrims confront injustice as much as monsters, restoring what has been buried and wronged.' },
  12: { zh:'火云洞中红孩儿纵火称雄，三昧真火烧得天地赤红。顽劣之心若能被度化，也能转成护法之力。', en:'Red Boy\'s Fire Cloud Cave burns with Samadhi Fire, yet even this fierce child can be guided toward a better path.' },
  13: { zh:'车迟国三大仙挟国王以压僧众，法术成了欺人的外衣。真正的修行，不靠虚张声势。', en:'At Cart Slow Kingdom, false immortals use spectacle to dominate others. Their fall exposes the difference between show and truth.' },
  14: { zh:'通天河冰深浪急，河中妖王借童男女求祭。渡河之前，先要渡过众人的恐惧。', en:'At the River of Heaven, a monster demands sacrifice. Before the pilgrims can cross the waters, they must cross the fear of the people.' },
  15: { zh:'女儿国无刀兵，却最动人心。唐僧的取舍，让西行第一次显出温柔也显出残忍。', en:'The Woman Kingdom offers no battlefield, only a human attachment so gentle that refusing it becomes its own ordeal.' },
  16: { zh:'解阳山芒硝泉一难，提醒众人肉身亦有限。哪怕神魔同行，也逃不开饥渴病痛与疲惫。', en:'At Jiyang Mountain, the hardships are bodily rather than martial, reminding the pilgrims that even heroes travel in fragile flesh.' },
  17: { zh:'盘丝洞丝网密布，美色与毒计齐下。西行路上，诱惑从来不会自称诱惑。', en:'Spider Cave wraps danger in silk and beauty, showing once again that temptation rarely arrives under its true name.' },
  18: { zh:'狮驼岭尸山血海，群妖设下重重围困。这里几乎像是取经路上一场真正的地狱。', en:'Lion Camel Ridge is one of the darkest reaches of the pilgrimage, where monstrous power turns the land itself into a nightmare.' },
  19: { zh:'比丘国以童子续命，国土表面安宁，实则邪法横行。师徒到来，便是要撕开这层伪善。', en:'Bhikshu Kingdom looks orderly on the surface, but hides cruelty beneath ritual and fear. The pilgrims force truth into the open.' },
  20: { zh:'火焰山炽热无边，挡在西去正路之上。若不能借得芭蕉扇，再大的志向也只能停在原地。', en:'The Flaming Mountain blocks the westward road completely. Without the Plantain Fan, even sacred purpose cannot move forward.' },
  21: { zh:'玉华州少年王子崇拜悟空师兄弟，也让这一路风霜第一次显出几分轻快。可好景不长，九灵元圣的阴影仍在前方。', en:'At Jade Flower Prefecture, admiration and hope briefly lighten the journey, though greater danger still waits ahead.' },
  22: { zh:'那烂陀临近天竺佛土，路上的气息终于由险恶转为庄严。走到这里，众人已不再是最初离开长安的人。', en:'Nalanda stands near the Buddhist heartlands. By the time the pilgrims reach it, they have already become different beings from those who left Chang\'an.' },
  23: { zh:'灵山雷音寺终于在云间显现。求经之路的终点，看似在西天，其实也在一路积累的心性之中。', en:'At last Thunderclap Monastery rises above the clouds. The destination lies in the West, but the scripture has been taking shape within the pilgrims all along.' },
};